### ISSUE TITLE
security based on IP

### ISSUE THREAD

**Issue by GChaucer** [ns3098/Pypuppeteer_Captcha_Solver#1]
Is this similar to other projects where it uses audio to text via api?
Wondering if this could flag the IP by google so that it wont allow more captchas to be solved.

can this also be used for chromium headless browsers that hit a captcha?

**Comment by ns3098** [comment]
Yes it uses Audio to text api.
Any captcha solver would be flagged by Google if you send large amount of requests. You must use proxy to avoid getting banned.

Yes it uses both head/headless chromium browser.
There are still some important things which i'll be updating once i get some free time.
